/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TariffRouteImport } from './routes/tariff'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookTaxiRouteImport } from './routes/book-taxi'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TariffRoute = TariffRouteImport.update({
  id: '/tariff',
  path: '/tariff',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTaxiRoute = BookTaxiRouteImport.update({
  id: '/book-taxi',
  path: '/book-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-taxi': typeof BookTaxiRoute
  '/contact': typeof ContactRoute
  '/tariff': typeof TariffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-taxi': typeof BookTaxiRoute
  '/contact': typeof ContactRoute
  '/tariff': typeof TariffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-taxi': typeof BookTaxiRoute
  '/contact': typeof ContactRoute
  '/tariff': typeof TariffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/book-taxi' | '/contact' | '/tariff'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/book-taxi' | '/contact' | '/tariff'
  id: '__root__' | '/' | '/about' | '/book-taxi' | '/contact' | '/tariff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookTaxiRoute: typeof BookTaxiRoute
  ContactRoute: typeof ContactRoute
  TariffRoute: typeof TariffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tariff': {
      id: '/tariff'
      path: '/tariff'
      fullPath: '/tariff'
      preLoaderRoute: typeof TariffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-taxi': {
      id: '/book-taxi'
      path: '/book-taxi'
      fullPath: '/book-taxi'
      preLoaderRoute: typeof BookTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookTaxiRoute: BookTaxiRoute,
  ContactRoute: ContactRoute,
  TariffRoute: TariffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
